# Generated by Django 3.1.2 on 2022-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('father_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('Class', models.CharField(default='', max_length=50)),
                ('section', models.CharField(default='', max_length=50)),
                ('roll_no', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
