# Generated by Django 3.1.2 on 2022-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_vidimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='vidimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vidimage'),
        ),
    ]
